// This is an autogenerated file from Firebase Studio.
"use client";

import Image from 'next/image';
import { Star } from 'lucide-react';
import type { Product } from '@/lib/types';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import WishlistButton from './wishlist-button';

interface ProductExpandedCardProps {
  product: Product;
}

export default function ProductExpandedCard({ product }: ProductExpandedCardProps) {
  const imageUrl = product.imageUrl || 'https://placehold.co/400x300.png';

  return (
    <Card className="w-full overflow-hidden border-primary border-2 mt-4">
      <CardContent className="p-4">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="md:col-span-1">
            <Image
              src={imageUrl}
              alt={product.name}
              width={400}
              height={300}
              className="w-full h-auto object-cover rounded-md"
              data-ai-hint="furniture product"
            />
          </div>
          <div className="md:col-span-2 space-y-4">
            <div>
                <h2 className="text-2xl font-bold tracking-tight">{product.name}</h2>
                <p className="text-2xl font-semibold text-primary mt-1">${product.price.toFixed(2)}</p>
            </div>
            <p className="text-muted-foreground text-sm">{product.description}</p>
            
            <div className="flex items-center gap-4">
              <Button size="lg" className="flex-1">Add to Cart</Button>
              <WishlistButton productId={product.id} />
            </div>

            <div>
              <h3 className="text-lg font-semibold mb-2">Customer Reviews ({product.reviews.length})</h3>
              <div className="space-y-3 max-h-40 overflow-y-auto">
                {product.reviews.length > 0 ? product.reviews.map(review => (
                  <div key={review.id} className="p-3 bg-secondary/50 rounded-lg text-sm">
                    <div className="flex items-center mb-1">
                      {Array.from({ length: 5 }).map((_, i) => (
                        <Star key={i} className={`h-4 w-4 ${i < review.rating ? 'text-yellow-400 fill-current' : 'text-muted-foreground'}`} />
                      ))}
                      <span className="ml-2 font-semibold">by {review.author}</span>
                    </div>
                    <p className="text-muted-foreground">{review.comment}</p>
                  </div>
                )) : <p className="text-sm text-muted-foreground">No reviews yet.</p>}
              </div>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
