// This is an autogenerated file from Firebase Studio.
import Link from 'next/link';
import Image from 'next/image';
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Check, Plus } from 'lucide-react';
import type { Product } from '@/lib/types';
import { cn } from '@/lib/utils';

interface ProductChatCardProps {
  product: Product;
  isSelected: boolean;
  onSelectToggle: () => void;
}

export default function ProductChatCard({ product, isSelected, onSelectToggle }: ProductChatCardProps) {
  const imageUrl = product.imageUrl || 'https://placehold.co/600x400.png';
  
  return (
    <Card className="flex flex-col h-full overflow-hidden transition-all duration-300">
      <CardHeader className="p-0 relative">
        <Image
            src={imageUrl}
            alt={product.name}
            width={300}
            height={200}
            className="w-full h-24 object-cover"
            data-ai-hint="furniture product"
          />
      </CardHeader>
      <CardContent className="p-2 flex-grow">
          <CardTitle className="text-sm font-medium tracking-tight hover:text-primary transition-colors line-clamp-2">
            {product.name}
          </CardTitle>
      </CardContent>
      <CardFooter className="p-2 pt-0 flex-col items-start">
        <p className="text-md font-semibold text-primary">${product.price.toFixed(2)}</p>
        <Button 
          variant={isSelected ? "default" : "outline"} 
          size="sm" 
          className="w-full mt-2"
          onClick={onSelectToggle}
        >
          {isSelected ? <Check className="mr-2 h-4 w-4" /> : <Plus className="mr-2 h-4 w-4" />}
          {isSelected ? 'Selected' : 'Select'}
        </Button>
      </CardFooter>
    </Card>
  );
}
