// This is an autogenerated file from Firebase Studio.
import { useState } from 'react';
import Image from 'next/image';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Check, Plus, ChevronDown, ChevronUp } from 'lucide-react';
import type { Product } from '@/lib/types';
import { cn } from '@/lib/utils';
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from './ui/collapsible';

interface ProductChatCardProps {
  product: Product;
  isSelected: boolean;
  onSelectToggle: () => void;
}

export default function ProductChatCard({ product, isSelected, onSelectToggle }: ProductChatCardProps) {
  const imageUrl = product.imageUrl || 'https://placehold.co/600x400.png';
  const [isDetailsOpen, setIsDetailsOpen] = useState(false);
  
  return (
    <Card className="flex flex-col h-full overflow-hidden transition-all duration-300">
      <CardHeader className="p-0 relative">
        <Image
            src={imageUrl}
            alt={product.name}
            width={300}
            height={200}
            className="w-full h-24 object-cover"
            data-ai-hint="furniture product"
          />
      </CardHeader>
      <Collapsible open={isDetailsOpen} onOpenChange={setIsDetailsOpen}>
        <CardContent className="p-2 flex-grow">
            <CardTitle className="text-sm font-medium tracking-tight hover:text-primary transition-colors line-clamp-2">
              {product.name}
            </CardTitle>
        </CardContent>
        <CollapsibleContent>
            <CardContent className="p-2 pt-0">
                <CardDescription className="text-xs line-clamp-3">
                    {product.description}
                </CardDescription>
            </CardContent>
        </CollapsibleContent>
        <CardFooter className="p-2 pt-0 flex-col items-start">
          <p className="text-md font-semibold text-primary">${product.price.toFixed(2)}</p>
          <div className="flex w-full mt-2 gap-2">
            <Button 
              variant={isSelected ? "default" : "outline"} 
              size="sm" 
              className="w-full"
              onClick={onSelectToggle}
            >
              {isSelected ? <Check className="mr-2 h-4 w-4" /> : <Plus className="mr-2 h-4 w-4" />}
              {isSelected ? 'Selected' : 'Select'}
            </Button>
            <CollapsibleTrigger asChild>
                <Button variant="outline" size="icon" className="shrink-0">
                    {isDetailsOpen ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
                    <span className="sr-only">Toggle Details</span>
                </Button>
            </CollapsibleTrigger>
          </div>
        </CardFooter>
      </Collapsible>
    </Card>
  );
}
